name: maxi_reflection
description: Personal library by Maximiliano Camilo for reflecting classes in Dart. It allows you to know a class's structure, its attributes, methods, and decorators at runtime
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  meta: ^1.17.0
  # path: ^1.9.0
  maxi_framework:
  #git:
    #  url: https://github.com/MaxiCamilo/maxi_framework.git
    #  ref: main
    path: ../maxi_framework

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
